//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourCompany.Modules.Test
{

    public partial class EditTest
    {
        protected DotNetNuke.UI.UserControls.LabelControl lblContent;
        protected DotNetNuke.UI.UserControls.TextEditor txtContent;
        protected System.Web.UI.WebControls.RequiredFieldValidator valContent;
        protected System.Web.UI.WebControls.LinkButton cmdUpdate;
        protected System.Web.UI.WebControls.LinkButton cmdCancel;
        protected System.Web.UI.WebControls.LinkButton cmdDelete;
        protected DotNetNuke.UI.UserControls.ModuleAuditControl ctlAudit;
    }
}
